schema = 1

[module]
id = "org.canopus.lyra-player"
version = "0.1.1"
language = "rust"
lifecycle = "resident-after-activation"
canopus_abi = "1"

[targets]
include = [
  "xiaomi-band-10-pro-3.101.036",
  "xiaomi-band-10-pro-3.101.043",
  "xiaomi-band-9-pro-3.1.175",
  "xiaomi-band-11-4.100.139",
  "xiaomi-band-11-4.100.155",
  "xiaomi-band-9-3.1.32",
]

[capabilities]
required = [
  "identity-guard",
  "native-app.register",
  "launcher.entry",
  "ui.dispatch",
  "interconnect.client",
  "nuttx.fs",
]

[native_app]
enabled = true
app_id = "org.canopus.lyra-player"
name = "Lyra"
entry = "canopus_module_descriptor"
role = "standalone"
